(()=>{
const API_URL=window.APP_CONFIG?.API_URL||'';const RESULTS_HOME_URL=window.APP_CONFIG?.RESULTS_HOME_URL||'./index.html';const STUDENT_TASKS_URL=window.APP_CONFIG?.STUDENT_TASKS_URL||'./student-tasks.html';const $=id=>document.getElementById(id);let session=null,data={tasks:[],freeReviews:[]};let currentImageData='';let editingFreeRecord=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const statusText={not_submitted:'尚未繳交',pending:'等待審核',approved:'已完成',rejected:'退回修改'};
function msg(t,type='error'){$('message').textContent=t||'';$('message').className=`message ${type}`}
async function requestJson(url,opt={}){const r=await fetch(url,{redirect:'follow',cache:'no-store',...opt});const text=await r.text();if(!r.ok)throw new Error(`API 連線失敗（HTTP ${r.status}）`);const x=text.trim();if(/^<!doctype|^<html/i.test(x))throw new Error('Apps Script 回傳 HTML，不是 JSON。請重新部署 Web App，並將存取權設為「任何人」。');let j;try{j=JSON.parse(x)}catch(e){console.error(text);throw new Error('API 回傳格式錯誤，請確認 Code.gs 已部署為最新版本。')}if(!j.success)throw new Error(j.message||'操作失敗');return j.data??j}
async function post(action,payload){return requestJson(API_URL+'?action='+encodeURIComponent(action),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})})}
async function loadPortal(studentName,cls){const qs=new URLSearchParams({action:'getStudentPortal',studentName:studentName,className:cls,_:Date.now()});return requestJson(`${API_URL}?${qs}`)}
function fmt(v){if(!v)return'—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleDateString('zh-TW')}
function safeNumber(v,fallback=0){if(v===null||v===undefined||v==='')return fallback;const n=Number(v);return Number.isFinite(n)?n:fallback}
function safeInt(v,min=0,max=Number.MAX_SAFE_INTEGER){return Math.min(max,Math.max(min,Math.round(safeNumber(v,min))))}
function stars(v){const n=safeInt(v,0,5);return '★'.repeat(n)+'☆'.repeat(5-n)}
function render(d){data=d;session={studentId:d.student.studentId,studentName:d.student.studentName,className:d.student.className,identityToken:d.identityToken||''};$('loginCard').hidden=true;$('studentApp').hidden=false;$('studentName').textContent=d.student.studentName||'同學';$('studentMeta').textContent=`${d.student.className}`;const all=[...(d.tasks||[]),...(d.freeReviews||[])];$('summary').innerHTML=`<div><strong>${(d.tasks||[]).length}</strong><span>指定任務</span></div><div><strong>${(d.freeReviews||[]).length}</strong><span>自由心得</span></div><div><strong>${all.filter(x=>(x.submissionStatus||x.status)==='pending').length}</strong><span>待審核</span></div><div><strong>${all.filter(x=>(x.submissionStatus||x.status)==='approved').length}</strong><span>已累積篇數</span></div>`;renderTasks();renderFree()}
function renderTasks(){const rows=data.tasks||[];$('tasks').innerHTML=rows.length?rows.map((t,i)=>{const st=t.submissionStatus||'not_submitted';return `<article class="task-card"><div class="task-top"><span class="status status-${st}">${statusText[st]||st}</span><span class="meta">截止 ${esc(fmt(t.dueDate))}</span></div><h3>${esc(t.title||t.bookTitle||'閱讀任務')}</h3><p>📖 ${esc(t.bookTitle||'未指定書名')}</p><p>${esc(t.description||'完成閱讀並撰寫心得。')}</p>${t.teacherFeedback?`<p class="teacher-comment">教師回饋：${esc(t.teacherFeedback)}</p>`:''}<button class="primary wide" data-task="${i}">${st==='approved'?'查看心得':st==='not_submitted'?'撰寫心得':'修改／查看心得'}</button></article>`}).join(''):'<div class="empty">目前沒有指定給你的閱讀任務。</div>'}
function renderFree(){const rows=data.freeReviews||[];$('freeReviews').innerHTML=rows.length?rows.map((r,i)=>`<article class="review-card"><div class="review-top"><span class="status status-${esc(r.status)}">${statusText[r.status]||r.status}</span><span class="meta">${esc(fmt(r.createdAt))}</span></div><h3>${esc(r.bookTitle)}</h3><div class="stars">${stars(r.rating)}</div><p>${esc(r.author)}｜${esc(r.publisher||'')}</p>${r.reviewContent?`<p>${esc(r.reviewContent.slice(0,110))}${r.reviewContent.length>110?'…':''}</p>`:'<p>🖼 圖片心得</p>'}${r.reviewImageUrl?`<img class="image-thumb" src="${esc(r.reviewImageUrl)}" alt="心得圖片">`:''}${r.teacherFeedback?`<p class="teacher-comment"><strong>教師退回原因：</strong>${esc(r.teacherFeedback)}</p>`:''}<div class="meta">${r.status==='approved'?'已審核通過並累積 1 篇':r.status==='rejected'?'請修改後重新送審':'等待教師審核'}</div>${r.status==='rejected'?`<button class="primary wide edit-free" data-free-edit="${i}">✏️ 修改心得並重新送審</button>`:''}</article>`).join(''):'<div class="empty">還沒有自由閱讀心得。選一本喜歡的書，開始第一篇吧！</div>'}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const studentName=$('loginStudentName').value.trim(),cls=$('className').value.trim();if(!API_URL)return msg('尚未設定 API_URL');if(!cls||!studentName)return msg('請輸入班級與姓名');msg('正在登入…','info');try{render(await loadPortal(studentName,cls));msg('')}catch(err){msg(err.message)}});
$('logoutBtn').onclick=()=>{session=null;data={tasks:[],freeReviews:[]};window.location.href=STUDENT_TASKS_URL};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));$('tabTasks').hidden=b.dataset.tab!=='tasks';$('tabFree').hidden=b.dataset.tab!=='free'});
$('tasks').addEventListener('click',e=>{const b=e.target.closest('[data-task]');if(!b)return;const t=data.tasks[Number(b.dataset.task)];$('taskModalTitle').textContent=t.title||t.bookTitle||'指定任務心得';const f=$('taskReviewForm');f.taskId.value=t.taskId;f.reviewTitle.value=t.reviewTitle||`${t.bookTitle||'閱讀'}心得`;f.pages.value=t.submittedPages||t.pages||0;f.reviewContent.value=t.reviewContent||'';f.isPublic.checked=!!t.isPublic;updateCounter(f.reviewContent,$('taskCounter'));$('taskModal').hidden=false});
$('taskReviewForm').reviewContent.addEventListener('input',e=>updateCounter(e.target,$('taskCounter')));
$('taskReviewForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;if(f.reviewContent.value.trim().length<100)return alert('指定任務心得至少需 100 字');try{await post('submitTaskReview',{studentId:session.studentId,studentName:session.studentName,className:session.className,identityToken:session.identityToken,taskId:f.taskId.value,reviewTitle:f.reviewTitle.value,pages:f.pages.value,reviewContent:f.reviewContent.value,isPublic:f.isPublic.checked});$('taskModal').hidden=true;render(await loadPortal(session.studentName,session.className));alert('已送出，等待教師審核。')}catch(err){alert(err.message)}});
function openFree(){editingFreeRecord=null;$('freeReviewForm').reset();currentImageData='';$('imagePreview').hidden=true;$('imagePreview').removeAttribute('src');updateCounter($('freeReviewText'),$('freeCounter'));$('submitFreeButton').textContent='送出心得，等待教師審核';$('freeModal').hidden=false}$('newFreeReview').onclick=openFree;$('newFreeReviewTop').onclick=openFree;

$('freeReviews').addEventListener('click',e=>{const b=e.target.closest('[data-free-edit]');if(!b)return;const r=(data.freeReviews||[])[Number(b.dataset.freeEdit)];if(!r||r.status!=='rejected')return;editingFreeRecord=r;const f=$('freeReviewForm');f.reset();f.bookTitle.value=r.bookTitle||'';f.author.value=r.author||'';f.publisher.value=r.publisher||'';f.rating.value=String(r.rating||'');f.reviewTitle.value=r.title||'';f.reviewContent.value=r.reviewContent||'';f.isPublic.checked=!!r.isPublic;currentImageData='';$('imagePreview').hidden=true;$('imagePreview').removeAttribute('src');updateCounter($('freeReviewText'),$('freeCounter'));$('submitFreeButton').textContent='重新送出審核';$('freeModal').hidden=false;});
$('freeReviewText').addEventListener('input',e=>updateCounter(e.target,$('freeCounter')));
function updateCounter(input,out){const n=input.value.trim().length;out.textContent=`${n} / 100 字`;out.classList.toggle('bad',n>0&&n<100)}
$('reviewImage').addEventListener('change',e=>{const file=e.target.files[0];currentImageData='';$('imagePreview').hidden=true;if(!file)return;if(file.size>5*1024*1024){e.target.value='';return alert('心得圖片不可超過 5MB')}if(!/^image\/(jpeg|png|webp)$/.test(file.type)){e.target.value='';return alert('只支援 JPG、PNG、WebP 圖片')}const reader=new FileReader();reader.onload=()=>{currentImageData=reader.result;$('imagePreview').src=currentImageData;$('imagePreview').hidden=false};reader.readAsDataURL(file)});
$('freeReviewForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),text=String(fd.get('reviewContent')||'').trim();if(text.length<100&&!currentImageData)return alert('請撰寫至少 100 字心得，或上傳心得圖片，二擇一');const btn=$('submitFreeButton');btn.disabled=true;btn.textContent='上傳中…';try{await post(editingFreeRecord?'resubmitFreeReview':'submitFreeReview',{recordId:editingFreeRecord?.recordId||'',studentId:session.studentId,studentName:session.studentName,className:session.className,identityToken:session.identityToken,bookTitle:fd.get('bookTitle'),author:fd.get('author'),publisher:fd.get('publisher'),rating:fd.get('rating'),reviewTitle:fd.get('reviewTitle'),reviewContent:text,reviewImageDataUrl:currentImageData,keepOldImage:!!(editingFreeRecord&&editingFreeRecord.reviewImageFileId&&!currentImageData),isPublic:fd.get('isPublic')==='on'});$('freeModal').hidden=true;render(await loadPortal(session.studentName,session.className));document.querySelector('[data-tab="free"]').click();alert(editingFreeRecord?'已重新送出，等待教師再次審核。':'心得已送出，教師審核通過後會累積 1 篇。');editingFreeRecord=null}catch(err){alert(err.message)}finally{btn.disabled=false;btn.textContent='送出心得，等待教師審核'}});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).hidden=true);document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.hidden=true}));
})();
